---
abstract: ~
author:
  - 'Christopher Nehren <apeiron@cpan.org>'
build_requires:
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: VirtualBox-Manage
no_index:
  directory:
    - inc
    - t
requires:
  Method::Signatures: 20081028
  Moose: 0.59
  Moose::Autobox: 0.09
  MooseX::Declare: 0.03
  MooseX::Method::Signatures: 0.06
  XML::LibXML: 1.66
resources:
  license: http://dev.perl.org/licenses/
version: 0.0.0
